Repository guardian/support-frontend, pull requests merged in 2019-09, with the labels that each got.

#2090 Restructure product cards
  support-frontend/assets/components/productOption/productOption.jsx
  support-frontend/assets/components/productOption/productOption.scss
  support-frontend/assets/components/productPage/productPageHero/productPageHero.scss
  support-frontend/assets/pages/digital-subscription-landing/components/digitalSubscriptionLandingHeader.jsx
  support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/__tests__/paymentSelectionTests.js
  support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/helpers/paymentSelection.jsx
  support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.jsx
  support-frontend/assets/pages/digital-subscription-landing/components/paymentSelection/paymentSelection.scss
  support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.jsx
  support-frontend/assets/pages/digital-subscription-landing/components/productBlockB/productBlockB.scss
  support-frontend/assets/pages/digital-subscription-landing/components/theMoment.scss
Labels: Do Not Merge

#2083 Update print sale copy in card on subs showcase page - do not merge until Monday 23 September 2019
  support-frontend/app/controllers/PaperSubscription.scala
  support-frontend/assets/components/headingBlock/headingBlock.scss
  support-frontend/assets/components/productPage/productPageTabs/productPageTabs.jsx
  support-frontend/assets/components/subscriptionBundle/subscriptionBundle.jsx
  support-frontend/assets/components/subscriptionBundles/paper.jsx
  support-frontend/assets/components/threeSubscriptions/threeSubscriptions.scss
  support-frontend/assets/helpers/flashSale.js
  support-frontend/assets/helpers/routes.js
  support-frontend/assets/helpers/subscriptions.js
  support-frontend/assets/helpers/theGrid.js
  support-frontend/assets/pages/paper-subscription-landing/components/content/form.jsx
  support-frontend/assets/pages/paper-subscription-landing/components/content/helpers.jsx
  support-frontend/assets/pages/paper-subscription-landing/components/hero/discountCopy.js
  support-frontend/assets/pages/paper-subscription-landing/components/hero/hero.jsx
  support-frontend/assets/pages/paper-subscription-landing/components/hero/joyOfPrint.scss
  support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.jsx
Labels: Do Not Merge

#2091 support workers read details from stripe in SCA mode if requested
  support-frontend/app/utils/CheckoutValidationRules.scala
  support-frontend/test/utils/CheckoutValidationRulesTest.scala
  support-models/src/main/scala/com/gu/support/workers/PaymentFields.scala
  support-models/src/test/scala/com/gu/support/workers/PaymentMethodIdTest.scala
  support-workers/src/main/scala/com/gu/stripe/Stripe.scala
  support-workers/src/main/scala/com/gu/stripe/StripeBrand.scala
  support-workers/src/main/scala/com/gu/stripe/StripeService.scala
  support-workers/src/main/scala/com/gu/stripe/createCustomerFromPaymentMethod.scala
  support-workers/src/main/scala/com/gu/stripe/createCustomerFromToken.scala
  support-workers/src/main/scala/com/gu/stripe/getPaymentMethod.scala
  support-workers/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
  support-workers/src/test/scala/com/gu/support/workers/JsonFixtures.scala
  support-workers/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
  support-workers/src/test/scala/com/gu/zuora/Fixtures.scala
Labels: Seen-on-PROD

#2099 use latest sbt version
  project/build.properties
Labels: Pending-on-PROD
