Repository guardian/support-frontend, pull requests merged in 2025-10, with the labels that each got.

#7343 Upgrade AWS SDK to Version 2 in support-frontend
  support-frontend/app/services/StripeSetupIntentService.scala
  support-frontend/app/services/aws/AwsAsync.scala
  support-frontend/app/services/aws/package.scala
  support-frontend/app/services/stepfunctions/Client.scala
  support-frontend/app/services/stepfunctions/StateMachineContainer.scala
  support-frontend/app/services/stepfunctions/SupportWorkersClient.scala
  support-frontend/app/services/stepfunctions/package.scala
  support-frontend/build.sbt
  support-frontend/test/services/stepfunctions/SupportWorkersClientTest.scala
  support-lambdas/acquisition-events-api/build.sbt
Labels: Maintenance, AWS SDK 1 -> 2

#7345 Premium Digital: Newspaper archive ThankYou module updates
  support-frontend/assets/components/thankYou/thankYouModule.tsx
  support-frontend/assets/components/thankYou/thankYouModuleData.tsx
  support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
Labels: Change failure fix

#7329 Guardian Weekly Gifting: checkout legal review changes
  support-frontend/assets/components/orderSummary/contributionsOrderSummary.tsx
  support-frontend/assets/components/orderSummary/orderSummaryTsAndCs.tsx
  support-frontend/assets/components/orderSummary/priceSummary.tsx
  support-frontend/assets/components/thankYou/thankYouModuleData.tsx
  support-frontend/assets/components/thankYou/whatNext/whatNext.tsx
  support-frontend/assets/helpers/forms/paymentMethods.ts
  support-frontend/assets/helpers/productCatalog.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
  support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
  support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
  support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/GuardianPrintHeading.tsx
  support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/StartDateMessage.tsx
  support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/heading.tsx
  support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/thankYouHeader.tsx
  support-frontend/assets/pages/supporter-plus-thank-you/components/thankYouHeader/utils/productMatchers.ts
  support-frontend/stories/checkouts/ContributionsOrderSummary.stories.tsx
Labels: Feature

#7350 Premium Digital: Landing Page Tier3 Card display DigitalSubscription benefits and copy
  support-frontend/assets/helpers/productCatalog.ts
  support-frontend/assets/pages/[countryGroupId]/checkout/helpers/benefitsChecklist.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
  support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/threeTierCard.tsx
  support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Labels: Feature

#7368 Adding /favicon.ico to the list of exclusions to the Observer Archive redirect
  support-frontend/conf/fastly-snippets/observerarchive-redirect-recv.vcl
Labels: Feature
