Repository guardian/support-frontend, pull requests merged in 2025-09, with the labels that each got.

#7236 Error handling for CreateZuoraSubscription lambda
  pnpm-lock.yaml
  pnpm-workspace.yaml
  support-workers/jest.config.js
  support-workers/src/main/scala/com/gu/support/workers/exceptions/CardDeclinedMessages.scala
  support-workers/src/typescript/errors/errorHandler.ts
  support-workers/src/typescript/errors/retryError.ts
  support-workers/src/typescript/errors/zuoraErrors.ts
  support-workers/src/typescript/lambdas/createPaymentMethodLambda.ts
  support-workers/src/typescript/lambdas/createSalesforceContactLambda.ts
  support-workers/src/typescript/lambdas/createZuoraSubscriptionTSLambda.ts
  support-workers/src/typescript/test/createPaymentMethodLambda.test.ts
  support-workers/src/typescript/test/createZuoraSubscriptionLambda.it.test.ts
  support-workers/src/typescript/test/errorHandler.test.ts
  support-workers/src/typescript/test/fixtures/createZuoraSubscription/transactionDeclinedInput.json
  support-workers/src/typescript/test/getZuoraPaymentMethod.test.ts
  support-workers/src/typescript/test/salesforce.it.test.ts
  support-workers/src/typescript/test/test-setup.ts
Labels: Feature

#7253 On the new newspaper plus landing page, collection should be the default tab
  support-frontend/assets/pages/paper-subscription-landing/components/NewspaperProductTabs.tsx
Labels: Feature

#7249 Adapt SupporterPlus email fields if the rate plan is fixed term
  support-workers/src/main/scala/com/gu/emailservices/SupporterPlusEmailFields.scala
  support-workers/src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
Labels: Feature

#7254 Newspaper Plus landing page card description copy
  support-frontend/assets/pages/[countryGroupId]/checkout/helpers/benefitsChecklist.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
  support-frontend/assets/pages/paper-subscription-landing/planData.tsx
Labels: Feature

#7250 Custom top up amounts for one time off contributions
  support-frontend/assets/helpers/utilities/__tests__/parseCustomAmounts.test.ts
  support-frontend/assets/helpers/utilities/utilities.ts
  support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.test.tsx
  support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
Labels: Feature

#7252 Use CreateZuoraSubscriptionTSLambda for Supporter Plus student plan
  cdk/lib/__snapshots__/support-workers.test.ts.snap
  cdk/lib/support-workers.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Feature

#7247 Don't trigger the create recurring product fail alarm for test users in prod
  support-frontend/app/actions/CustomActionBuilders.scala
  support-frontend/app/wiring/ActionBuilders.scala
  support-frontend/test/actions/ActionRefinerTest.scala
  support-frontend/test/controllers/ApplicationTest.scala
  support-frontend/test/controllers/SiteMapTest.scala
  support-frontend/test/fixtures/DisplayFormMocks.scala
Labels: Maintenance

#7275 NewPaper Plus Digital: Url Anchor tag added for fulfilmentOption tab switching
  support-frontend/assets/helpers/__tests__/routes.test.ts
  support-frontend/assets/helpers/productCatalog.ts
  support-frontend/assets/helpers/urls/routes.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
  support-frontend/assets/pages/paper-subscription-landing/components/NewspaperProductTabs.tsx
  support-frontend/assets/pages/paper-subscription-landing/helpers/windowSetHashProperty.tsx
  support-frontend/assets/pages/paper-subscription-landing/paperSubscriptionLandingPage.tsx
Labels: Feature

#7295 Only add tab anchor to URL when the user selects a tab
  support-frontend/assets/pages/paper-subscription-landing/components/NewspaperProductTabs.tsx
Labels: Feature

#7286 NewPaper Plus Digital: Switch-On Production Only
  support-frontend/assets/pages/paper-subscription-landing/helpers/inPaperProductTest.ts
Labels: Feature

#7296 Add SSM param containing ALB ARN for support-frontend
  cdk/lib/__snapshots__/frontend.test.ts.snap
  cdk/lib/frontend.ts
Labels: Maintenance

#7281 Enable ALB access logs for support-frontend (CODE only)
  cdk/bin/cdk.ts
  cdk/lib/__snapshots__/frontend.test.ts.snap
  cdk/lib/frontend.test.ts
  cdk/lib/frontend.ts
Labels: Maintenance

#7301 NewPaper Plus Digital: SummaryTsAndCs Paper Copy Fix
  support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.test.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/summaryTsAndCs.tsx
  support-frontend/stories/checkouts/SummaryTsAndCs.stories.tsx
Labels: Change failure fix

#7304 Rename `SupportInternationalisationId` to `SupportRegionId`
  pnpm-lock.yaml
  pnpm-workspace.yaml
  support-frontend/assets/components/countryGroupSwitcher/countryGroupSwitcher.tsx
  support-frontend/assets/components/headers/links/links.tsx
  support-frontend/assets/components/subscriptionCheckouts/address/addressFields.tsx
  support-frontend/assets/helpers/forms/paymentIntegrations/readerRevenueApis.ts
  support-frontend/assets/helpers/internationalisation/Readme.md
  support-frontend/assets/helpers/productCatalog.ts
  support-frontend/assets/helpers/productPrice/__tests__/productPricesTests.ts
  support-frontend/assets/helpers/subscriptionsForms/submit.ts
  support-frontend/assets/helpers/urls/externalLinks.ts
  support-frontend/assets/helpers/urls/routes.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
  support-frontend/assets/pages/[countryGroupId]/components/formOnSubmit.ts
  support-frontend/assets/pages/[countryGroupId]/components/oneTimeCheckoutComponent.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/oneOffCard.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/studentOffer.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/supportOnce.tsx
  support-frontend/assets/pages/weekly-subscription-landing/components/weeklyProductPrices.tsx
Labels: Feature

#7317 Enable OK actions for product acquisition alarms
  cdk/lib/__snapshots__/support-workers.test.ts.snap
  cdk/lib/frontend.ts
  cdk/lib/support-workers.ts
Labels: Maintenance

#7326 Fix missing billing country on digital only subs
  support-workers/src/typescript/services/salesforce.ts
  support-workers/src/typescript/test/salesforce.test.ts
Labels: Change failure fix

#7307 Student Page: Enable index for global student pages
  support-frontend/app/controllers/Application.scala
Labels: Change failure fix, Feature

#7331 PremiumDigital: Remove Ab test and create feature flag
  support-frontend/assets/helpers/abTests/abtestDefinitions.ts
  support-frontend/assets/helpers/featureFlags.ts
  support-frontend/assets/helpers/productCatalog.ts
  support-frontend/assets/helpers/productPrice/billingPeriods.ts
  support-frontend/assets/pages/[countryGroupId]/components/checkoutForm.tsx
  support-frontend/assets/pages/[countryGroupId]/components/checkoutSummary.tsx
  support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
  support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Labels: Change failure fix

#7309 Fix Guardian Weekly checkout promo terms link
  support-frontend/assets/helpers/legal.ts
  support-frontend/assets/pages/promotion-terms/legalTerms.tsx
  support-frontend/assets/pages/promotion-terms/weeklyTerms.tsx
  support-frontend/assets/pages/supporter-plus-landing/components/__snapshots__/paymentTsAndCs.test.tsx.snap
  support-frontend/assets/pages/supporter-plus-landing/components/paymentTsAndCs.tsx
Labels: Change failure fix

#7337 Upgrade S3 to v2 in payment-api
  support-payment-api/build.sbt
  support-payment-api/src/main/scala/MyApplicationLoader.scala
  support-payment-api/src/main/scala/aws/AWSClientBuilder.scala
  support-payment-api/src/main/scala/backend/PaypalBackend.scala
  support-payment-api/src/main/scala/backend/StripeBackend.scala
  support-payment-api/src/main/scala/services/SwitchService.scala
  support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
Labels: Maintenance, AWS SDK 1 -> 2

#7339 Upgrade SQS to v2 in payment-api
  support-payment-api/build.sbt
  support-payment-api/src/main/scala/aws/AWSClientBuilder.scala
  support-payment-api/src/main/scala/backend/StripeBackend.scala
  support-payment-api/src/main/scala/services/ContributionsStoreService.scala
  support-payment-api/src/main/scala/services/EmailService.scala
  support-payment-api/src/test/scala/backend/PaypalBackendSpec.scala
  support-payment-api/src/test/scala/backend/StripeBackendSpec.scala
  support-payment-api/src/test/scala/services/EmailServiceSpec.scala
Labels: Maintenance, AWS SDK 1 -> 2
