Repository guardian/support-frontend, pull requests merged in 2025-04, with the labels that each got.

#6897 Refactor landing page test participations
  support-frontend/assets/helpers/abTests/__tests__/landingPageAbTests.spec.ts
  support-frontend/assets/helpers/abTests/abtest.ts
  support-frontend/assets/helpers/abTests/landingPageAbTests.ts
  support-frontend/assets/helpers/abTests/mvt.ts
  support-frontend/assets/helpers/page/page.ts
  support-frontend/assets/helpers/redux/utils/setup.ts
  support-frontend/assets/pages/[countryGroupId]/checkout.tsx
  support-frontend/assets/pages/[countryGroupId]/components/__tests__/thankYouComponent.test.tsx
  support-frontend/assets/pages/[countryGroupId]/components/checkoutComponent.tsx
  support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
  support-frontend/assets/pages/[countryGroupId]/landingPage.tsx
  support-frontend/assets/pages/[countryGroupId]/router.tsx
  support-frontend/assets/pages/[countryGroupId]/thankYou.tsx
  support-frontend/assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx
Labels: Pending-on-PROD

#6882 Implement design change to Sunday only (Observer only) product card
  support-frontend/assets/components/product/productOption.tsx
  support-frontend/assets/components/product/productOptionStyles.tsx
  support-frontend/assets/helpers/productPrice/productOptions.ts
  support-frontend/assets/pages/paper-subscription-landing/components/content/paperPrices.tsx
  support-frontend/assets/pages/paper-subscription-landing/components/paperProductPrices.tsx
  support-frontend/assets/pages/paper-subscription-landing/helpers/products.ts
  support-frontend/assets/pages/paper-subscription-landing/helpers/shouldShowObserver.ts
  support-frontend/assets/pages/weekly-subscription-landing/components/content/prices.tsx
  support-frontend/stories/product/ProductOption.stories.tsx
Labels: design-reviewed

#6912 Different email campaigns for Sunday only
  support-workers/src/main/scala/com/gu/emailservices/PaperEmailFields.scala
Labels: Pending-on-PROD

#6929 Push the newspaperGenericCheckout variant live to all users
  support-frontend/assets/helpers/abTests/abtestDefinitions.ts
Labels: Pending-on-PROD

#6958 Observer: Landing Page Cards & Checkout enabled in Production
  support-frontend/assets/pages/paper-subscription-landing/helpers/shouldShowObserver.ts
Labels: Do Not Merge

#6963 ThankYou page layout fixs
  support-frontend/assets/components/thankYou/thankyouModules.tsx
  support-frontend/assets/pages/[countryGroupId]/components/thankYouComponent.tsx
Labels: design-reviewed
